version: 2

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: projector
    hooks:
      post:
        - cmd: chmod +x {{ .Path }}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

homebrew_casks:
  - name: projector
    repository:
      owner: joelgrimberg
      name: homebrew-tap
    homepage: "https://github.com/joelgrimberg/projector"
    description: "A CLI application for project and action management"
