name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      releases_created: ${{ steps.semantic.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug Output
        run: |
          echo "Semantic release outputs:"
          echo "new_release_version: ${{ steps.semantic.outputs.new_release_version }}"
          echo "new_release_published: ${{ steps.semantic.outputs.new_release_published }}"
          echo "releases_created: ${{ steps.semantic.outputs.releases_created }}"

  linux:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release_version != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install cross compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Build Linux binaries
        run: |
          # Build linux binaries
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-linux-gnu-gcc go build -ldflags="-s -w" -o dist/projector_linux_amd64/projector .
          GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc go build -ldflags="-s -w" -o dist/projector_linux_arm64/projector .
          
          # Create archives
          cd dist
          tar -czf projector_linux_amd64.tar.gz projector_linux_amd64/
          tar -czf projector_linux_arm64.tar.gz projector_linux_arm64/
          cd ..
          
          # Create checksums
          cd dist
          shasum -a 256 *.tar.gz > checksums_linux.txt
          cd ..
      - name: Debug semantic-release outputs
        run: |
          echo "new_release_version: ${{ needs.semantic-release.outputs.new_release_version }}"
          echo "new_release_published: ${{ needs.semantic-release.outputs.new_release_published }}"
          echo "releases_created: ${{ needs.semantic-release.outputs.releases_created }}"
      - name: Upload Linux binaries to release
        if: needs.semantic-release.outputs.releases_created != ''
        run: |
          # Get the release upload URL from GitHub API
          RELEASE_ID=$(gh api repos/joelgrimberg/projector/releases/latest --jq '.id')
          UPLOAD_URL="https://uploads.github.com/repos/joelgrimberg/projector/releases/$RELEASE_ID/assets"
          
          # Upload AMD64 binary
          gh api $UPLOAD_URL \
            -F name="projector_linux_amd64.tar.gz" \
            -F label="Linux AMD64 Binary" \
            -F file=@./dist/projector_linux_amd64.tar.gz
          
          # Upload ARM64 binary
          gh api $UPLOAD_URL \
            -F name="projector_linux_arm64.tar.gz" \
            -F label="Linux ARM64 Binary" \
            -F file=@./dist/projector_linux_arm64.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Linux ARM64 binary to release
        if: needs.semantic-release.outputs.releases_created != ''
        run: |
          # Get the release upload URL from GitHub API
          RELEASE_ID=$(gh api repos/joelgrimberg/projector/releases/latest --jq '.id')
          UPLOAD_URL="https://uploads.github.com/repos/joelgrimberg/projector/releases/$RELEASE_ID/assets"
          
          # Upload ARM64 binary
          gh api $UPLOAD_URL \
            -F name="projector_linux_arm64.tar.gz" \
            -F label="Linux ARM64 Binary" \
            -F file=@./dist/projector_linux_arm64.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  darwin:
    runs-on: macos-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release_version != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build macOS binaries
        run: |
          # Build darwin binaries
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build -ldflags="-s -w" -o dist/projector_darwin_amd64/projector .
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 go build -ldflags="-s -w" -o dist/projector_darwin_arm64/projector .
          
          # Create archives
          cd dist
          tar -czf projector_darwin_amd64.tar.gz projector_darwin_amd64/
          tar -czf projector_darwin_arm64.tar.gz projector_darwin_arm64/
          cd ..
          
          # Create checksums
          cd dist
          shasum -a 256 *.tar.gz > checksums_darwin.txt
          cd ..
      - name: Debug semantic-release outputs
        run: |
          echo "new_release_version: ${{ needs.semantic-release.outputs.new_release_version }}"
          echo "new_release_published: ${{ needs.semantic-release.outputs.new_release_published }}"
          echo "releases_created: ${{ needs.semantic-release.outputs.releases_created }}"
      - name: Upload macOS AMD64 binary to release
        if: needs.semantic-release.outputs.releases_created != ''
        run: |
          # Get the release upload URL from GitHub API
          RELEASE_ID=$(gh api repos/joelgrimberg/projector/releases/latest --jq '.id')
          UPLOAD_URL="https://uploads.github.com/repos/joelgrimberg/projector/releases/$RELEASE_ID/assets"
          
          # Upload AMD64 binary
          gh api $UPLOAD_URL \
            -F name="projector_darwin_amd64.tar.gz" \
            -F label="macOS AMD64 Binary" \
            -F file=@./dist/projector_darwin_amd64.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload macOS ARM64 binary to release
        if: needs.semantic-release.outputs.releases_created != ''
        run: |
          # Get the release upload URL from GitHub API
          RELEASE_ID=$(gh api repos/joelgrimberg/projector/releases/latest --jq '.id')
          UPLOAD_URL="https://uploads.github.com/repos/joelgrimberg/projector/releases/$RELEASE_ID/assets"
          
          # Upload ARM64 binary
          gh api $UPLOAD_URL \
            -F name="projector_darwin_arm64.tar.gz" \
            -F label="macOS ARM64 Binary" \
            -F file=@./dist/projector_darwin_arm64.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Homebrew formula
        run: |
          mkdir -p dist/homebrew/Formula
          cat > dist/homebrew/Formula/projector-cli.rb << 'EOF'
          class ProjectorCli < Formula
            desc "A CLI application for project and action management"
            homepage "https://github.com/joelgrimberg/projector"
            version "${{ needs.semantic-release.outputs.new_release_version }}"
            license "MIT"
            
            on_macos do
              if Hardware::CPU.arm?
                url "https://github.com/joelgrimberg/projector/releases/download/v#{version}/projector_darwin_arm64.tar.gz"
                sha256 "$(shasum -a 256 dist/projector_darwin_arm64.tar.gz | cut -d' ' -f1)"
              else
                url "https://github.com/joelgrimberg/projector/releases/download/v#{version}/projector_darwin_amd64.tar.gz"
                sha256 "$(shasum -a 256 dist/projector_darwin_amd64.tar.gz | cut -d' ' -f1)"
              end
            end
            
            on_linux do
              if Hardware::CPU.arm?
                url "https://github.com/joelgrimberg/projector/releases/download/v#{version}/projector_linux_arm64.tar.gz"
                sha256 "$(shasum -a 256 dist/projector_linux_arm64.tar.gz | cut -d' ' -f1)"
              else
                url "https://github.com/joelgrimberg/projector/releases/download/v#{version}/projector_linux_amd64.tar.gz"
                sha256 "$(shasum -a 256 dist/projector_linux_amd64.tar.gz | cut -d' ' -f1)"
              end
            end
            
            def install
              bin.install "projector"
            end
            
            test do
              system "#{bin}/projector", "--version"
            end
          end
          EOF
      - name: Push Homebrew formula to tap
        env:
          TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          rm -rf tap
          git clone https://x-access-token:${TAP_TOKEN}@github.com/joelgrimberg/homebrew-tap.git tap
          
          # Remove old cask file if it exists
          rm -f tap/Casks/projector.rb
          
          # Create Formula directory and add new formula
          mkdir -p tap/Formula
          cp dist/homebrew/Formula/projector-cli.rb tap/Formula/projector-cli.rb
          
          cd tap
          git add Formula/projector-cli.rb
          git rm -f Casks/projector.rb 2>/dev/null || true
          
          if git diff --cached --quiet; then
            echo "No formula changes to commit."
          else
            git commit -m "Update projector-cli formula for ${{ needs.semantic-release.outputs.new_release_version }}"
            git push https://x-access-token:${TAP_TOKEN}@github.com/joelgrimberg/homebrew-tap.git HEAD:main
          fi